### ISSUE TITLE
Clearly separate dates

### ISSUE THREAD

**Issue by RmMsr** [eurucamp/eurucamp-activities#116]
It should be easier to see what activity is on which day. Maybe by visual separation or by a filter.

**Comment by maser** [comment]
How would we handle events that span multiple days? Show them on the day they start?

Are we already hiding past events?

**Comment by moonglum** [comment]
If they span multiple days we should probably show them on every one of those days. My other idea was to just forbid events that span multiple days. If this edge case occurs, people can just create multiple events.
