### ISSUE TITLE
Build Activities app on Codeship & deploy on Codeship

### ISSUE THREAD

**Issue by bascht** [eurucamp/eurucamp-activities#117]
- [x] bump dependencies
- [x] kill defective cldwalker/debugger#125 gem
- [x] migrate Travis stuff to codeship
- [x] check with @bitboxer if we want to run this thing on :shell:-y-:partly_sunny: 
- [ ] link the production one to run on rubyweek.org

**Comment by bascht** [comment]
@bitboxer while I'm at it: Do we want to run the activities app on Shellycloud as well? (I'd :+1: this)

**Comment by bitboxer** [comment]
Why not :wink: .

**Comment by bascht** [comment]
@bitboxer Didn't expect anything else. Just wanted to check. :)

**Comment by moonglum** [comment]
@bascht Can you help bitboxer to finish the last bit of this task (making it available on rubyweek.eurucamp.org)?

**Comment by moonglum** [comment]
Also we need to nuke activities.eurucamp.org :wink:

**Comment by bascht** [comment]
@moonglum I'm on holidays starting next monday, so if @maser or @pxlpnk could take over, that'll be grand. :)

**Comment by moonglum** [comment]
This is done. We will run on http://rubyweek.eurucamp.org for now, maybe add rubyweek.org later.
