### ISSUE TITLE
Mark events that require an eurucamp ticket

### ISSUE THREAD

**Issue by moonglum** [eurucamp/eurucamp-activities#119]
Events that are part of the special eurucamp afternoon should be marked with the eurucamp Logo and it should be clear that you need a Ticket to attend this event.

**Comment by skade** [comment]
Do you need to? It was quite common that some people would just pass by the eurucamp to participate in the lunch break.

**Comment by maser** [comment]
Who is allowed to create activities that require a ticket? Do I add a check box to the form? Or do we set a flag via Rails console?

I intend to put a eurucamp flag logo on the `#index` tiles and prominently at the top in `#show` with a title/alt explaining what it means. Also the same text in the "required" section in `#show`. 

I’ll just grab that flag logo from the style guide header.

**Comment by bitboxer** [comment]
I think this should be setable by everone who creates a activity. I think we should word it something like "during the eurucamp, participants need a ticket"

**Comment by bitboxer** [comment]
And @skade: we do not want to advertise that people can participate without a ticket on the events that take part on the eurucamp break. We will not check this or inforce this, but more tickets sold is more important right now  :wink:

**Comment by maser** [comment]
Index view:

![screenshot from 2015-06-28 14 12 11](https://cloud.githubusercontent.com/assets/2545/8396272/b64b65b8-1d9f-11e5-8ffc-db2c412083d7.png)

Detail view:

![screenshot from 2015-06-28 14 11 52](https://cloud.githubusercontent.com/assets/2545/8396274/bb3285f2-1d9f-11e5-82f4-6248e7459cce.png)

Feedback?
