### ISSUE TITLE
Order activitites by start time

### ISSUE THREAD

**Issue by sferik** [eurucamp/eurucamp-activities#146]
I took a peek at the code to look at how this might be done. Unfortunately, the solution is not as simple as changing https://github.com/eurucamp/eurucamp-activities/blob/f5c62819d52c25d7c73313ecd00e6216691cfcd6/app/models/event.rb#L71 to sort by `activity.start_time` instead of `activity.dates.first`, since not every activity has a start time (e.g. anytime events).

I also noticed there was already a `Activity#order_by_start_time` scope, where the logic seems to be:
* First upcoming events chronologically
* Then anytime events
* Then events whose end time has already past

So, I think the solution is to implement an instance method that implements the same logic to call from within `Event#activities_per_day`.

**Comment by maser** [comment]
Oh, I borked the order of activities :(

I am on it, it actually is as simple as changing it to order by start time since we removed anytime activities (#145).

How to handle activities whose end time has already passed is also on my list, I just created #147 for that.
