### ISSUE TITLE
Handle past activities

### ISSUE THREAD

**Issue by maser** [eurucamp/eurucamp-activities#147]
We used to put activities whose end time has already passed at the end of the list. We now group activities by date, so we can't just append them at the end.

I suggest we add another group at the end 'Past Activities' that collects all of these.

**Comment by bitboxer** [comment]
why not leave activities where they are? they are sorted by date, so I can scroll to the current ones easily

**Comment by maser** [comment]
That is okay with me, there are not too may of them anyway and it is less work.
