### ISSUE TITLE
Allow switching to previous/next months in calendar (date picker)

### ISSUE THREAD

**Issue by dcarral** [eurucamp/eurucamp-activities#166]
Currently we're disabling the ability to switch to a different month within the calendar shown in the date picker (hiding the arrows).

@moonglum: is there a good reason to do that? It's currently provoking that when trying to create/edit a new activity (at least nowadays, August, 2015), it's not possible to set start/end in the same month (using the date picker widget). 

Fwiw, it can be easily fixed by removing the explicit `display:none` @ [`app/assets/stylesheets/_pickadate_overrides.sass`](https://github.com/dcarral/eurucamp-activities/blob/upgrade_to_pickadate_v3.5.6/app/assets/stylesheets/_pickadate_overrides.sass) (PR https://github.com/eurucamp/eurucamp-activities/pull/165).

**Comment by moonglum** [comment]
I agree, there is no good reason for that!
