### ISSUE TITLE
Cannot deploy on Heroku

### ISSUE THREAD

**Issue by Hoverbear** [eurucamp/eurucamp-activities#173]
There are two issues:

* `eventmachine` does not build, this can be fixed by updating the `Gemfile.lock`. PR #174.
* `/usr/sbin/sendmail` does not exist on Heroku anymore, and this causes the application to fail completely.

**Comment by skade** [comment]
Don't ever edit Gemfile.lock manually. :)

Update Gemfile and reresolve.

**Comment by lucaspinto** [comment]
:p

**Comment by Hoverbear** [comment]
Fixing the mailer issue was accomplished with:

```ruby
  config.action_mailer.smtp_settings = {
    address: "#{ENV['MAILGUN_SMTP_SERVER']}",
    port: "#{ENV['MAILGUN_SMTP_PORT']}",
    user_name: "#{ENV['MAILGUN_SMTP_LOGIN']}",
    password: "#{ENV['MAILGUN_SMTP_PASSWORD']}"
  }
```

:)
