### ISSUE TITLE
Submitting the form via enter key sets focus to first time capture field

### ISSUE THREAD

**Issue by polarblau** [eurucamp/eurucamp-activities#55]
Very peculiar bug: Instead submitting the form when the enter key is pressed, the time select flashes by:

**Reproduce**

* Focus on title field
* Hit enter

**Comment by elfenars** [comment]
The issue was tried to be reproduced today and it seems to be solved.
Since the bug is pretty old, maybe it got solved, please confirm. :rocket:

**Comment by moonglum** [comment]
Awesome :smile: Let me close that!
